apiVersion: v1
kind: Service
metadata:
  name: 'modelservice'  # Replace with your desired service name
spec:
  type: LoadBalancer
  selector:
    app: credit
  ports:
  - port: 80
    targetPort: 9696
